name: Build

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    name: build affected
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup
        uses: ./.github/actions/local-action

      - name: Build
        run: yarn nx affected --target=build --parallel=3
