name: Build

on:
  workflow_call:
    inputs:
      base_branch:
        type: string
        default: "main" # TODO : CHANGE TO MASTER
        required: false
        description: "Reference branch for nx affected"

jobs:
  build:
    runs-on: ubuntu-latest
    name: build affected
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup
        uses: ./.github/actions/setup

      - name: Build
        run: yarn nx affected --target=build --parallel=3 --
