name: End To End Test

on:
  workflow_call: {}

jobs:
  e2e:
    runs-on: ubuntu-latest
    name: e2e affected
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup
        uses: ./.github/actions/setup

      - name: Build
        run: yarn nx affected --target=e2e --parallel=3
