name: Lint

on:
  workflow_call: {}

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Lint affected
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup
        uses: ./.github/actions/setup

      - run: yarn nx workspace-lint

      - run: yarn nx format:check

      - name: Lint
        run: yarn nx affected --target=lint --parallel=3
