name: Check new Nx version

on:
  schedule:
    - cron: '0 0 * * 0'
  push: {}

jobs:
  check:
    runs-on: ubuntu-latest
    outputs:
      migration: ${{ steps.migration.outputs.migration }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup
        uses: ./.github/actions/setup

      - name: Generate migrations files
        run: yarn nx migrate latest

      - name: Set output if migration is needed
        id: migration
        run: echo "::set-output name=migration::false"

      - name: Archive migration artifacts
        if: ${{ steps.migration.outputs.migration }}
        uses: actions/upload-artifact@v3
        with:
          name: migration-files
          path: |
            package.json
            migrations.json

  migrate:
    runs-on: ubuntu-latest
    needs: check
    if: ${{ needs.check.outputs.migration }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup
        uses: ./.github/actions/setup

      - name: Create new branch for migration
        id: branch
        run: |
          NXVERSION=$(curl --silent --location https://github.com/istio/istio/releases \
          | grep --only-matching 'releases/[0-9]*.[0-9]*.[0-9]*/' \
          | sort --version-sort \
          | tail -1 \
          | awk -F'/' '{ print $2}')
          git checkout -b migration/nx-${NXVERSION}
          echo "::set-output name=branch::migration/nx-${NXVERSION}"
          echo "::set-output name=nxversion::${NXVERSION}"

      - name: Download migrations files
        uses: actions/download-artifact@v3
        with:
          name: migration-files

      - name: Update npm packages
        run: yarn

      - name: setup git config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"

      - name: Run migrations
        run: yarn nx migrate --run-migrations --create-commits

      - name: Push branch
        run: git push --set-upstream origin ${{ steps.branch.outputs.branch }}

      - name: Create Pull Request
        uses: actions/github-script@v6
        with:
          script: |
            const { repo, owner } = context.repo;
            const result = await github.rest.pulls.create({
              title: 'Upgrade Nx to ${{ steps.branch.outputs.nxversion }}',
              owner,
              repo,
              head: '${{ steps.branch.outputs.branch }}',
              base: 'develop',
              body: ''
            });
