name: Pull Request

on:
  pull_request: {}
  push: {}

jobs:
  lint:
    uses: ./.github/workflows/lint-affected.yml

  test:
    needs: lint
    uses: ./.github/workflows/test-affected.yml

  build:
    needs: test
    uses: ./.github/workflows/build-affected.yml
