name: Pull Request

on:
  pull_request: {}
  pull_request_review:
    types: [submitted]

jobs:
  lint:
    if: github.event.review.state == 'approved' || github.event_name == 'pull_request'
    uses: ./.github/workflows/lint-affected.yml

  build:
    needs: lint
    uses: ./.github/workflows/build-affected.yml

  test:
    needs: build
    uses: ./.github/workflows/test-affected.yml
